const actions={
   SET_USER:"SET_USER",
   SET_PRODUCTOS:"SET_PRODUCTOS",
   TOGGLE_CARRITO:"TOGGLE_CARRITO",
   SET_CARRITO:"SET_CARRITO",
   UPDATE_CARRITO:"UPDATE_CARRITO",
   SET_PEDIDOS:"SET_PEDIDOS"





}
export default actions;